// AUTO-GENERATED by scripts/gen-registry.mjs — do not edit by hand.
// Regenerate with `npm run gen:registry` (also runs as part of `npm run build`).
//
// A filesystem-free mirror of the blog registry, so the Cloudflare Pages
// Function at /api/analytics can join GA page paths to real titles.

export type RegistryEntry = {
  slug: string;
  path: string;
  title: string;
  category: string;
  date: string;
};

export const POST_REGISTRY: RegistryEntry[] = [
  {
    "slug": "turtle-nesting-season-pomene",
    "path": "/journal/turtle-nesting-season-pomene",
    "title": "Turtle Nesting Season in Pomene, Mozambique: When and How to See Them (October–March)",
    "category": "Wildlife",
    "date": "2026-08-17"
  },
  {
    "slug": "self-catering-vs-all-inclusive-mozambique",
    "path": "/journal/self-catering-vs-all-inclusive-mozambique",
    "title": "Self-Catering vs All-Inclusive in Mozambique: Which Suits Your Trip? (2026)",
    "category": "Off-Grid",
    "date": "2026-08-07"
  },
  {
    "slug": "diving-snorkelling-pomene",
    "path": "/journal/diving-snorkelling-pomene",
    "title": "Diving & Snorkelling in Pomene: Reefs Few Ever Reach",
    "category": "Things to Do",
    "date": "2026-07-30"
  },
  {
    "slug": "whale-watching-pomene-mozambique",
    "path": "/journal/whale-watching-pomene-mozambique",
    "title": "Whale Watching in Pomene, Mozambique: When, Where & How to See Humpbacks (2026)",
    "category": "Wildlife",
    "date": "2026-07-10"
  },
  {
    "slug": "pomene-travel-guide",
    "path": "/journal/pomene-travel-guide",
    "title": "Pomene Travel Guide (2026): How to Get There, Best Time to Visit & Things to Do",
    "category": "Travel Guide",
    "date": "2026-06-10"
  },
  {
    "slug": "drive-to-pomene-4x4-guide",
    "path": "/journal/drive-to-pomene-4x4-guide",
    "title": "Driving to Pomene: Do You Really Need a 4×4? (Routes, Tyre Pressure & Timing)",
    "category": "Getting There",
    "date": "2026-05-28"
  },
  {
    "slug": "best-time-to-visit-pomene",
    "path": "/journal/best-time-to-visit-pomene",
    "title": "The Best Time to Visit Pomene: Whales, Turtles, Fishing & Weather Month by Month",
    "category": "Seasons",
    "date": "2026-05-15"
  }
];

export const PAGE_REGISTRY: RegistryEntry[] = [
  {
    "slug": "home",
    "path": "/",
    "title": "Home",
    "category": "Page",
    "date": ""
  },
  {
    "slug": "journal",
    "path": "/journal",
    "title": "Journal",
    "category": "Page",
    "date": ""
  }
];

/** Every known path, posts first. */
export const ALL_ENTRIES: RegistryEntry[] = [...POST_REGISTRY, ...PAGE_REGISTRY];

/** Look up an entry by GA pagePath, tolerating trailing slashes and query strings. */
export function lookupPath(pagePath: string): RegistryEntry | undefined {
  const clean = pagePath.split("?")[0].replace(/\/$/, "") || "/";
  return ALL_ENTRIES.find((e) => e.path === clean);
}
